### ISSUE TITLE
MIDI2RMID does not write padding bytes

### ISSUE THREAD

**Issue by sagamusix** [adamrehn/assorted-utils#2]
Hello Adam,
RIFF files (no matter if AVI, WAV, RMID or whatever) demand chunks to be aligned to multiples of two.
That is, if a chunk's size is odd, it should be padded with a zero byte to make the next chunk start at an even offset (but the length in the chunk header should not contain this padding byte, i.e. it should remain odd).
MIDI2RMID does not currently do this, so if the original MID file has an odd size, a compliant player (e.g. DirectMusic) will be unable to find the DLS chunk, as the "data" chunk is missing a padding byte.

So if `(midiSize % 2) == 1`, you should add one to `rmidSize` and write a padding byte after the `copyFileData(midiFileStream, rmidFileStream);` call.

**Comment by adamrehn** [comment]
Whoops, silly me, you're absolutely correct. Thanks for catching that! Fixed now.
